[tool.poetry]
name = "textual-autocomplete"
version = "3.0.0a11"
description = "Easily add autocomplete dropdowns to your Textual apps."
authors = ["Darren Burns <darrenb900@gmail.com>"]
readme = "README.md"
packages = [{ include = "textual_autocomplete" }]

[tool.poetry.dependencies]
python = "^3.8"
#textual = {path="../textual", develop=true}
textual = ">=0.58.0"
typing-extensions = "^4.5.0"

[tool.poetry.group.dev.dependencies]
mypy = "^0.991"
black = "^22.10.0"
textual = { version = ">=0.58.1", extras = ["dev"] }
ward = { version = "^0.67.2b0", allow-prereleases = true }
textual-dev = "^1.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
