[tool.poetry]
name = "textual-autocomplete"
version = "2.0.0b0"
description = "Easily add autocomplete dropdowns to your Textual apps."
authors = ["Darren Burns <darrenb900@gmail.com>"]
readme = "README.md"
packages = [{ include = "textual_autocomplete" }]

[tool.poetry.dependencies]
python = "^3.7.8"
#textual = {path="../textual", develop=true}
textual = "^0.11.0"
typing-extensions = "^4.5.0"

[tool.poetry.group.dev.dependencies]
mypy = "^0.991"
black = "^22.10.0"
#textual = { version = "^0.10.0", extras = ["dev"] }
textual = { version = "^0.11.0", extras = ["dev"] }
ward = { version = "^0.67.2b0", allow-prereleases = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
