[tool.poetry]
name = "textual-autocomplete"
version = "0.1.0"
description = ""
authors = ["Darren Burns <darrenb900@gmail.com>"]
readme = "README.md"
packages = [{include = "textual_autocomplete"}]

[tool.poetry.dependencies]
python = "^3.7.8"
textual = "^0.5.0"


[tool.poetry.group.dev.dependencies]
mypy = "^0.991"
black = "^22.10.0"
ward = "^0.67.0b0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
